### ISSUE TITLE
cubi-tk snappy pull-raw-data is slow for large studies

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#155]
**Describe the bug**
In a study with ~1.5k samples, `cubi-tk snappy pull-raw-data` is slower than it should be.

**To Reproduce**
```
$ cubi-tk snappy pull-raw-data 17328747-5a36-43bc-900d-5941008c872a
[I 230126 05:58:52] Will start at REDACTED/GRCh37
[I 230126 05:58:52] Loading configuration file and look for dataset
[I 230126 05:58:52] => will download to REDACTED/RAW_DATA
[I 230126 05:58:52] Will start at REDACTED/GRCh37
[I 230126 05:58:52] Starting remote files search ...
[I 230126 05:58:52] 4 iRODS connections initialized
[I 230126 05:58:52] Querying for data objects
```

Then you wait.

**Expected behavior**
N/A

**Additional context**
Apparently, this uses the iRODS file traversal API. It should be much faster to use the equivalent of `iquest`.

**Comment by xiamaz** [comment]
Closed via https://github.com/bihealth/cubi-tk/pull/184
