### ISSUE TITLE
`cubi-tk snappy`is not yet adapted to new/renamed snappy steps

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [bihealth/cubi-tk#165]
**Describe the bug**
The snappy step dependencies in cubi-tk/snappy/common do currently not fully match the state of snappy. This means that i.e. `cubi-tk snappy kickoff`will not start certain steps, other tools may be affected as well.

These currently defined steps have been renamed in or removed from snappy:
- roh_calling [removed without replacement?]
- variant_export
- targeted_seq_cnv_calling
- targeted_seq_cnv_annotation
- targeted_seq_cnv_export
- wgs_sv_calling
- wgs_sv_annotation
- wgs_sv_export
- wgs_cnv_calling
- wgs_cnv_annotation
- wgs_cnv_export

These steps in snappy are likely replacements or additions that may need definition in cubi-tk
- helper_gcnv_model_targeted & helper_gcnv_model_wgs
  - newly added steps (?)
- sv_calling_targeted
  - replaces: targeted_seq_cnv_calling
- sv_calling_wgs
  - replaces: wgs_sv_calling & wgs_cnv_calling
- varfish_export
  - replaces: wgs_sv_export & wgs_cnv_export & (?) targeted_seq_cnv_export
- variant_annotation
  - replaces: wgs_sv_annotation, wgs_cnv_annotation & (?) targeted_seq_cnv_annotation
- variant_export_external
  - likely a replacement for  wgs_cnv_export_external & wgs_sv_export_external, though those are still in use?
- variant_checking, variant_denovo_filtration, variant_filtration, variant_phasing
   - unclear if cubi-tk support is needed?

Support for these steps was not included in cubi-tk and is probably not needed:   
- General NGS: adapter_trimming, ngs_data_qc, ngs_mapping, ngs_sanity_checking, 
- RNAseq: gene_expression_quantification, gene_expression_report
- Various: cbioportal_export, hla_typing, tcell_crg_report, igv_session_generation, panel_of_normals, repeat_analysis
- somatic_*:
  - somatic_hla_loh_calling, somatic_msi_calling, somatic_gene_fusion_calling, somatic_neoepitope_prediction, somatic_ngs_sanity_checking, somatic_purity_ploidy_estimate, somatic_targeted_seq_cnv_calling, somatic_variant_annotation, somatic_variant_calling, somatic_variant_checking, somatic_variant_expression, somatic_variant_filtration, somatic_variant_signatures, somatic_wgs_cnv_calling, somatic_wgs_sv_calling, 

**To Reproduce**
1. Create a snappy project with of the currently not supported steps
2. run `cubi-tk snappy kickoff`
The unsupported steps will not be run.

**Expected behavior**
Cubi-tk should be updated to have support for at least all steps used in routine analysis of WGS & WES data for genetics.
A likely list of steps that should ahve support is given above.

**Comment by xiamaz** [comment]
Yes, am currently experiencing similar issues with a legacy pipeline with steps named `helper_gcnv_model_targeted`, `sv_calling_targeted` and `varfish_export`
