### ISSUE TITLE
Update to isa-tab not working when `i_Investigation.txt` is not in same subfolder as AssayData and SampleSheet

### ISSUE THREAD

**Issue by your-highness** [bihealth/cubi-tk#190]
**Describe the bug**
For SODAR project `1f59198a-358c-43a4-9d5e-0e34b3cfcfad` I can not update project SampleSheet and AssayData via `cubi-tk sodar add-ped` or `cubi-tk sodar upload-sheet` because `i_Investigation.txt` is placed in `./isatab` subfolder. Log outputs:

```bash
[I 230802 08:52:46] Starting cubi-tk sodar add-ped
[I 230802 08:52:46]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, dry_run=False, show_diff=False, show_diff_side_by_side=False, sample_name_normalization='snappy', batch_no='18', yes=True, library_type='WES', library_layout='PAIRED', library_kit='Agilent SureSelect Human All Exon V8', library_kit_catalogue_id='S33266340', instrument_model='Illumina NovaSeq 6000', no_warnings=False, platform='ILLUMINA', project_uuid='1f59198a-358c-43a4-9d5e-0e34b3cfcfad', input_ped_file=<_io.TextIOWrapper name='/scratch/helmuth/tmp/iRODS_sodar_1f59198a-358c-43a4-9d5e-0e34b3cfcfad_2308.tsv/v8.ped' mode='rt' encoding='UTF-8'>)
[I 230802 08:52:46] -- downloading sample sheet --
[I 230802 08:52:46] Starting cubi-tk sodar download-sheet
[I 230802 08:52:46]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, makedirs=False, overwrite=False, dry_run=False, yes=True, show_diff=False, show_diff_side_by_side=False, project_uuid='1f59198a-358c-43a4-9d5e-0e34b3cfcfad', output_dir='/tmp/tmpr4vuw1gx')
[I 230802 08:52:47] Writing /tmp/tmpr4vuw1gx/isatab/i_Investigation.txt
[I 230802 08:52:47] About to write file contents to /tmp/tmpr4vuw1gx/isatab/i_Investigation.txt
Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/cubi-tk/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/__init__.py", line 93, in run
    return args.sodar_cmd(args, parser, subparser)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/add_ped.py", line 142, in run
    return cls(Config(**args)).execute()
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/add_ped.py", line 167, in execute
    yes=True,
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/download_sheet.py", line 135, in execute
    out_path, isa_dict["investigation"]["path"], isa_dict["investigation"]["tsv"]
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/download_sheet.py", line 163, in _write_file
    show_diff_side_by_side=self.config.show_diff_side_by_side,
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/common.py", line 254, in overwrite_helper
    with out_path_obj.open("wt") as output_file:
  File "/opt/conda/miniconda3/envs/cubi-tk/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/opt/conda/miniconda3/envs/cubi-tk/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpr4vuw1gx/isatab/i_Investigation.txt'
```

```bash
[I 230802 09:04:48] Starting cubi-tk sodar upload-sheet
[I 230802 09:04:48]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, project_uuid='1f59198a-358c-43a4-9d5e-0e34b3cfcfad', input_investigation_file='samplesheet/isatab/i_Investigation.txt')
Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/cubi-tk/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/__init__.py", line 93, in run
    return args.sodar_cmd(args, parser, subparser)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/upload_sheet.py", line 68, in run
    return cls(Config(**args)).execute()
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/upload_sheet.py", line 90, in execute
    isa_data = isa_support.load_investigation(self.config.input_investigation_file)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/isa_support.py", line 48, in load_investigation
    with (i_path.parent / study.info.path).open() as s_file:
  File "/opt/conda/miniconda3/envs/cubi-tk/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/opt/conda/miniconda3/envs/cubi-tk/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'samplesheet/isatab/s_*****.txt'
```

**To Reproduce**
1. Start samplesheet update via `cubi-tk sodar add-ped`
2. Get error message

**Expected behavior**
An update should work via  `cubi-tk sodar add-ped` or `cubi-tk sodar add-ped` .

**Additional context**
See also internal issue under https://gitlab.cubi.bihealth.org/cubi-collaborations/cubi-medgen/-/issues/140

**Workaround**
A workaround is to use `cubi-tk sodar download-sheet`  to download all ISATAB files and manually move `i_Investigation` from `./isatab` subfolder into root to be alongside SampleSheet and AssayData. A local isatab update via  `cubi-tk isa-tab add-ped`  followed by an upload via `cubi-tk sodar upload-sheet 1f59198a-358c-43a4-9d5e-0e34b3cfcfad ./i_Investigation.txt` gives expected results. However, I am not sure if there now exist two files `i_Investigation.txt` in the project, _i.e._ one in root and one in `./isatab`

**Comment by your-highness** [comment]
@xiamaz

**Comment by your-highness** [comment]
> This is a bit odd. ~Does this only happen for this project?~

Also project `4ad70119-1beb-4505-a17a-fe2c05b15f89` 

> I've understood you placed the i_Investigation.txt in `./isatab/` on purpose. Why is that? Also, is this live on SODAR? Does `cubi-tk sodar download-sheet` include this subfolder?

I did not place the files there. We are only contributing data and I saw that my update via `cubi-tk add-ped` does not work correctly. I will switch to `cubi-tk sodar download-sheet ..` & `cubi-tk isa-tab add-ped` for now. 

The main problem here is that project might contain multiple incoherent versions of SampleSheet files in various subfolders.

> The reason you're seeing these errors is probably due to the fact that the ISA-tab internal file locations do not consider this additional subfolder i.e. `cubi-tk sodar add-ped` looks for s_* and a_* files in `./isatab` and does not find any because they are in `./`

I presumed that this is the reason.

**Comment by Nicolai-vKuegelgen** [comment]
I've just looked into they output of `cubi-tk sodar download sheet 4ad70119-1beb-4505-a17a-fe2c05b15f89 test` and there was no ./isatab folder present - is this different for you (or did you already update that project now?)

**Comment by your-highness** [comment]
> I've just looked into they output of `cubi-tk sodar download sheet 4ad70119-1beb-4505-a17a-fe2c05b15f89 test` and there was no ./isatab folder present - is this different for you (or did you already update that project now?)

That's correct! I updated both project already with the last batches. For last update of `4ad70119-1beb-4505-a17a-fe2c05b15f89` via `cubi-tk sodar add-ped` I got a TextIOWrapper error:
```bash
[I 231007 17:36:49] Starting cubi-tk sodar add-ped
[I 231007 17:36:49]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, dry_run=False, show_diff=False, show_diff_side_by_side=False, sample_name_normalization='snappy', batch_no='3', yes=True>
[I 231007 17:36:49] -- downloading sample sheet --
[I 231007 17:36:49] Starting cubi-tk sodar download-sheet
[I 231007 17:36:49]   config: Config(config=None, verbose=False, sodar_server_url=None, sodar_url='https://sodar.bihealth.org/', sodar_api_token=***, makedirs=False, overwrite=False, dry_run=False, yes=True, show_diff=False, show_diff_side_by_side=False, project_uuid='4>
[I 231007 17:36:49] Writing /tmp/tmpcky0jspu/i_Investigation.txt
[I 231007 17:36:49] About to write file contents to /tmp/tmpcky0jspu/i_Investigation.txt
[I 231007 17:36:49] Writing /tmp/tmpcky0jspu/s_medgen_exomes_selektivvertrag.txt
[I 231007 17:36:49] About to write file contents to /tmp/tmpcky0jspu/s_medgen_exomes_selektivvertrag.txt
[I 231007 17:36:49] Writing /tmp/tmpcky0jspu/a_medgen_exomes_selektivvertrag.txt
[I 231007 17:36:49] About to write file contents to /tmp/tmpcky0jspu/a_medgen_exomes_selektivvertrag.txt
[I 231007 17:36:49] -- downloading sheet succeeeded --
[I 231007 17:36:49] -- updating sample sheet --
[I 231007 17:36:49] Starting cubi-tk isa-tab add-ped
[I 231007 17:36:49]   config: Config(verbose=False, config=None, sodar_server_url=None, sodar_api_token=***, no_warnings=False, sample_name_normalization='snappy', yes=True, dry_run=False, show_diff=False, show_diff_side_by_side=False, batch_no='3', library_layout='PAIR>
Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/cubi-tk/bin/cubi-tk", line 33, in <module>
    sys.exit(load_entry_point('cubi-tk', 'console_scripts', 'cubi-tk')())
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/__main__.py", line 123, in main
    res = cmds[args.cmd](args, parser, subparsers.choices[args.cmd] if args.cmd else None)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/__init__.py", line 93, in run
    return args.sodar_cmd(args, parser, subparser)
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/add_ped.py", line 142, in run
    return cls(Config(**args)).execute()
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/sodar/add_ped.py", line 197, in execute
    input_ped_file=self.config.input_ped_file,
  File "/opt/software/HUM/cubi-tk.new/cubi_tk/isa_tab/add_ped.py", line 674, in execute
    with open(self.config.input_ped_file, "rt") as inputf:
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
```

**Comment by sellth** [comment]
Ok, this looks like an unrelated issue. In fact, I believe this one was fixed in #127/#128 and your version of cubi-tk is just outdated. Please update by either running
```
git pull origin main
pip install -e .
```
or by [starting over](https://github.com/bihealth/cubi-tk/tree/main#getting-started) with a new conda environment as we recommend Python 3.10 by now and updated a few dependencies.

That being said, please let us know if there's another SODAR project which is currently having the issue of creating a `isatab/` subfolder for i_Investigation.txt after `cubi-tk sodar download-sheet`.

**Comment by your-highness** [comment]
@sellth You are right! Our cubi-tk was really outdated with version `0.2.0+47.g23ca740`. I installed from `cubi-tk/release v0.3.1`:
```bash
>cubi-tk --version
cubi-tk 0.3.0+66.ge0dbd46
```

Now I can use `cubi-tk sodar add-ped` correctly! 

Thanks for assistance.

**Comment by sellth** [comment]
That's great to hear! I would however recommend to install from `main`. I'll try to push a new release v0.4.0 soon.

**Comment by sellth** [comment]
Those branches are automatically created and deleted by our release system. If you want reproducible installs, you should aim for one of the tagged releases. The latest release has quite a lot of bug fixes and new features which is why v0.3.1 was skipped. I would therefore recommend using it like so: `git fetch && git checkout v0.4.0 && pip install -e .` 

That being said, if you still have the commit hash previously tagged as branch *release-v0.3.1* you can also install from there: `git checkout <hash>`

**Comment by your-highness** [comment]
I don't track the git hash because a branch existed. For now I will work with 0.4.0 and try to keep the hash.

**Comment by sellth** [comment]
No need to track the hash for v0.4.0 as this commit is tagged.
