### ISSUE TITLE
Need to adjust to varfish-cli changes

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#197]
**Is your feature request related to a problem? Please describe.**
After bihealth/varfish-cli#61 we will have to adjust the call to `varfish-cli` as we cannot call `main()` directly any more.

**Describe the solution you'd like**
Switch this to a `subprocess.Popen()` call.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Nicolai-vKuegelgen** [comment]
Implemented as of #222
