### ISSUE TITLE
Newest varfish-cli is not compatible with python 3.8

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [bihealth/cubi-tk#214]
**Describe the bug**
cubi-tk CI currently tests against python 3.8, 3.9 & 3.10.
cubi-tk also imports the varfish-cli (which tests 3.10-3.12). The varfish-cli started using `typing.Annotated` in version 0.6.*, which is not available in python 3.8 and thus breaks the cubi-tk tests run under that version.

**To Reproduce**
- try/check any recent CI run that installs varfish-cli >= 0.6.* 

**Expected behavior**
Since we likely want to keep using the newest varfish-cli version, it seems that we need to drop python 3.8 support.

**Comment by sellth** [comment]
Easiest fix: Update our python versions to 3.10+

**Comment by Nicolai-vKuegelgen** [comment]
Circumvented as of #222
