### ISSUE TITLE
CI workflow fails with newest snappy version

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [bihealth/cubi-tk#236]
**Describe the bug**
The current cubi-tk installation depends on snappy. However, with the recent snappy 0.2 releases it seems that cubi-tk fails to install properly.

**To Reproduce**
Run CI or try to install from scratch in an empty environment

**Expected behavior**
Installation & CI need to work.  
We should either pin the snappy version or update the cubi-tk build/install process to work with the newer versions.

**Comment by Nicolai-vKuegelgen** [comment]
Example: https://github.com/bihealth/cubi-tk/actions/runs/10452794729/job/28941957961?pr=235

**Comment by tedil** [comment]
I'd suggest we pin the snappy-pipeline version to v0.1.1 for now, and then in a second step check and update cubi-tk requirements and potentially bump snappy-pipeline to v0.2.x

**Comment by Nicolai-vKuegelgen** [comment]
Sounds goods / seems to fix the issue for now - I'll close this as solved
