### ISSUE TITLE
Add "cubi-tk isa-tab annotate" command

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#3]
The aim is to be able to support the following use cases:

- annotate sources with their HLA types stored in a TSV file
- annotate samples with QC statistics such as read counts etc.

The input would be:

- folder with ISA-tab files
- path to annotation TSV file
- which assay/study to annotate
- name of the output column

The output would be

- folder with ISA-tab files where the study/assay files are updated to reflect the annotations

For example (pseudo ISA-tab)

input ISA-tab has

Source Name | Sample Name
------------|------------
SampleA | SampleA-N1
SampleB | SampleB-N1
SampleC | SampleC-N1

Annotation has

Source Name | HLA Type
------------|---------
SampleA | A:01:01;A01:02
SampleC | A:03:01;A03:02

Result is

Source Name | HLA Type | Sample Name
------------|----------|------------
SampleA | A:01:01;A01:02 | SampleA-N1
SampleB | | SampleB-N1
SampleC | A:03:01;A03:02 | SampleC-N1

We can then also create a `cubi-tk sodar isa-tab-annotate` that does it to the ISA-tab of a SODAR project.

cc @ericblanc20

**Comment by ericblanc20** [comment]
HLA types are attributes of the source. It would be good if it was possible to choose at which level these attributes belong. For example, the proportion of cancer cells in a tumor sample (purity) is something important for the clinicians. That would be an attribute of the sample (in case there are several samples for one donor).

**Comment by bobermayer** [comment]
isn't this also a case for updating sample sheet meta-data directly on the server (see [here](https://cubi-gitlab.bihealth.org/CUBI_Engineering/CUBI_Data_Mgmt/sodar/-/issues/1026))? if we get ISAtab files output we would have to replace the entire sample sheet, with no check that non-updated values did not change

**Comment by mkuhring** [comment]
ca4c4c0dac6a260e1bc24d0d26ec8ce84e850ba7 could be already used for simple annotation. I.e. with one study and one assay and Materials to be annotated are already available in the isa-tab (i.e. no new nodes / rows will be created).
