### ISSUE TITLE
Make snappy itransfer commands autodiscover the biomedsheets file

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#33]
**Is your feature request related to a problem? Please describe.**
You have to pass the file to the biomedsheets file on the command line.

**Describe the solution you'd like**
It would be more consistent with the behaviour of other tools to specify the project UUID and auto-discover the config.yaml file by crawling up the directory tree until `.snappy_pipeline` is found. Then look there for the appropriate TSV file based on the configuration.

**Comment by eudesbarbosa** [comment]
Implemented in #54
