### ISSUE TITLE
snappy-itransfer does not re-use existing landing zones

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#35]
**Describe the bug**
Consecutive calls to the `snappy-itransfer` commands create multiple landing zones.

**To Reproduce**
Consecutively call `snappy-itransfer` multiple times.

**Expected behavior**
The commands should re-use existing landing zones from the current user.

**Additional context**
N/A

**Comment by eudesbarbosa** [comment]
How was the tool called? I would expect that behaviour something like the example below, i.e., for each call there will be a new LZ. 
If `--yes` is set, it doesn't check if there are LZs available. Rational: avoid any potential conflict between users. Reuse of LZs is only possible in interact mode and if `--validate-and-move` is _**not**_ set.

```
# variant calling files
cubi-tk snappy itransfer-variant-calling --start-batch 99.snappy_pipeline/project_name.tsv \
	--yes --validate-and-move <UUID>
# ngs mapping files
cubi-tk snappy itransfer-ngs-mapping --start-batch 99.snappy_pipeline/project_name.tsv \
	--yes --validate-and-move <UUID>

# `--yes`: Assume all answers are yes, e.g., will create or use existing available landing zones without asking.
# `--validate-and-move`: after files are transferred to SODAR, it will proceed with validation and move them.
```

**Comment by holtgrewe** [comment]
The behaviour is as you describe. There probably was a problem with the specification.

Users cannot interact as each sandbox is only visible to the current user. The current user UUID can be fetched to a recently added API.

**Comment by holtgrewe** [comment]
The rationale is that the call to the itransfer commands should be idempotent. So by default we should be able to repeat the call with the default parameters and nothing should change remotely.
