### ISSUE TITLE
Rename cubi-tk isa-tpl sub commands

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#42]
**Is your feature request related to a problem? Please describe.**
All `cubi-tk` command names use `kebab-case`... all commands? No, a growing number of templates in `cubi-tk isa-tpl` don't! They should

**Describe the solution you'd like**
Rename the commands with `s/_/-/g`.

**Describe alternatives you've considered**
Keep it like this but that's inconsistent.

**Additional context**
N/A

**Comment by sellth** [comment]
By now all template commands consistently use snake case. Closing this.
