### ISSUE TITLE
cubi-tk snappy varfish-upload does not understand joining by family

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#46]
**Describe the bug**
Create sample sheet for SNAPPY that uses the join-by-family feature (e.g., two siblings). Process the data. Then, run `cubi-tk snappy varfish-upload`. It will try to find the files for the second sample and then crash.

**Expected behavior**
It should exhibit the same behaviour as the SNAPPY pipeline.

**Additional context**
N/A

**Comment by eudesbarbosa** [comment]
Best case scenario: two working days including tests. Relatively easy (if assumptions hold).

**Issues:**
- Missing attribute `pedigree_field` in `models::Dataset`.
- New attribute must be used while loading the sheet in `varfish_upload::load_sheet_tsv()`.
