### ISSUE TITLE
Improve consistency of cubi-tk snappy sub commands

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#51]
**Is your feature request related to a problem? Please describe.**
1. Harmonize `--start-batch` and similarly named arguments. Add `--last-batch` (maybe harmonize towards `--first-batch`/`--last-batch).
2. The `itransfer-*` commands want paths to biomed sheets. They should rather ask for UUIDs.

**Describe the solution you'd like**
Implement the harmonization / simplification for users.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by eudesbarbosa** [comment]
Regarding point *2*, I don't thing we can easily get rid of the biomed sheet argument. The library names are extracted from there, and probably okay to just use the local copy of the data.

Code: [Line 625](https://github.com/bihealth/cubi-tk/blob/master/cubi_tk/snappy/itransfer_common.py#L625)

**Comment by holtgrewe** [comment]
We can read `.snappy_pipeline/config.yaml` and get the TSV path from there.

**Comment by eudesbarbosa** [comment]
OK, on it!

**Comment by eudesbarbosa** [comment]
This changes make the landing zone option inviable. Is it okay if I remove it?
Option *1* here: [L343](https://github.com/bihealth/cubi-tk/blob/master/cubi_tk/snappy/itransfer_common.py#L343)
