### ISSUE TITLE
Refurbish cubi-tk irods check

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#59]
**Is your feature request related to a problem? Please describe.**
The current implementation is not so practical (any more). For example, it actually downloads the files and computes md5 check sums which is not practical for really large directories and uses icommands in too many places rather than the Python API.

**Describe the solution you'd like**
Change it as follows:

- Use Python API for the parts that don't do heavy lifting
- Perform checks:
    - count replicas
    - check that md5 sum exists for all replicas and is consistent
    - check that the file length of all replicas is the same
    - check that 0-sized files have the md5sum of the empty string `d41d8cd98f00b204e9800998ecf8427e`
- Optionally, download file and compute md5 sums (opt-in)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mikkonie** [comment]
We don't actually have to separately check the file size, since we're already comparing checksums.
