### ISSUE TITLE
pull data from SODAR from assay with missing samples

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/cubi-tk#60]
**Is your feature request related to a problem? Please describe.**
`cubi-tk sodar pull-raw-data` fails when some samples described in the assay table don't have (yet) data in SODAR/iRODS.

This can happen when the data collection plan is put in the ISATAB sample & assay tables, but only part of the samples have been sequenced & stored in SODAR.

**Describe the solution you'd like**
`cubi-tk sodar pull-raw-data` could check if a data directory exists for each sample, prior to downloading the data. That behaviour could be toggled by the user, from the command line.

**Describe alternatives you've considered**
The other option is to keep the sample & assay tables in sync with the data currently available. It puts a much greater emphasis on samples bookkeeping.

**Comment by eudesbarbosa** [comment]
Closed by #61
