### ISSUE TITLE
Tools for CEPH archive

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/cubi-tk#67]
**The problem**
Archiving older projects to CEPH should follow strict SOP. `cubi-tk` is a good place to make sure that the SOP is enforced.

**Proposed solution**
`cubi-tk archive` sub-commands for:

- Finding dangling links, links unaccessible because of permissions, links pointing outside of the project directory,
- Finding `*.fastq.gz` raw data file & their associated md5 checksum file (possibly computing them if unavailable),
- List large files from unknown origin that could be public data (`*.fa`, `*.gtf`, `SRA*`, ...)
- Prepare for archive: check presence of `README.md`, tar-gzip `.snakemake` directories & remove them
- performing the archive commands: checking the preparation steps, `hashdeep`, `rsync` to CEPH, check `, audit hashdeep & remove original

**Alternatives**
The final archiving command might be split, to enable fine-grained control over the archive.

**Comment by eudesbarbosa** [comment]
@ericblanc20, as we discuss, we can probably decoupled the SODAR check from this step.
Issue #56 underdevelopment already.

**Comment by ericblanc20** [comment]
**Examples**

- `2017-01-20_Wanker_Alz`: ~700GB, contains fastq files that are on SODAR, and fastq dangling links to files that may be on SODAR too. 
- `2015-12-03_panomics2015`: contains bam files presumably corresponding to dangling links to fastq files.
- `2016-09-28_tumor_wes_playground`: files pointing to the store and to another project.
