### ISSUE TITLE
Make "cubi-tk sodar itransfer-*" more convenient to use

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#8]
Status quo of the workflow:

- go to SODAR, create landing zone, copy path in iRODS
- use the `cubi-tk snappy itransfer-X` data on the command line with the path to iRODS
- go to SODAR, submit landing zone

The following workflow would be much more convenient:

- call `cubi-tk snappy itransfer-init $project_uuid` to create a landing zone (warn the user if it already exists and ask them whether to create a new one)
- call `cubi-tk snappy itransfer-X $project_uuid` to transfer data into the latest landing zone (warn if none exists, prompt user whether to createa  new one)
- call `cubi-tk snappy itransfer-finalize $project_uuid` to submit the landing zone for submission and validation (optionally only validate if `--only-validate` is given)

Hints:

- reuse the `cubi-tk sodar` sub command classes for querying SODAR (or use the APIs used therein)
- there are pleny of examples on how to re-use the internal command clases to compose specialized commands (`snappy itransfer` should already serve as an example)

**Comment by eudesbarbosa** [comment]
**Assessment**: The two required functionalities already exist in `cubi-tk`, namely: list and create landing zone. 

**Suggestion:** Move the iRODS path functionality from `SnappyItransferCommandBase._build_jobs()` to a new method, e.g., 
`SnappyItransferCommandBase.get_irods_path()`. Additionally create new flag `create-lz`. 
Use cases:
1. If iRODS path provided, use it.
2. If project UUID provided in combination with flag `create-lz`, create new landing zone.
3. If only project UUID provided, check if any landing zone is available. If there is at least one landing zone available, ask 
user to select which one to use. If there is no landing zone available, ask user if a new one should be created.

Pseudo-code:
```
def get_irods_path(destination, create_lz_flag):
	lz_path = None
	if destination is iRODS path:
		lz_path = destination
	if destination is UUID:
		if create_lz_flag:
			create new lz based on uuid
			lz_path = new lz path
		else:
			list available lz options
			if lz available:
				lz_path = user selected lz path
			else:
				ask if user wants to create new lz
				if yes:
					create new lz based on uuid
					lz_path = new lz path
	return lz_path
```

**Comment by holtgrewe** [comment]
The most common use case will be (a) no landing zone exists (b) user wants to create a new one.

IOW:

1. if iRODS path then use it
2. if landing zone UUID then use it
3. if project UUID then
    - get most recently created landing zone and
        - select it if any
        - if none then decide to create new one
    - ask user if that's OK

Also

- add `--yes` parameter
- allow the user to provide landing zone UUID to select a particular one only
