### ISSUE TITLE
Archive rules proposals

### ISSUE THREAD

**Issue by ericblanc20** [bihealth/cubi-tk#81]
The archival process should tar & compress `.snakemake` directories to reduce inodes counts on the ceph system. `cubi-tk archive prepare` is responsible for that.

Other files & directories might be ignored or compressed, without loss of information on the copy.

**Compress directories**:
- `.snakemake`
-  `sge_log`
- `.git`

**Ignore files** (don't copy them to ceph):
- core dumps `^core.[0-9]+$`

Other candidates?

**Comment by messersc** [comment]
Ignore:

* .venv (moving a venv breaks it AFAIK)

Compress:

* cubi_wrappers ?
* cubi_pipeline ?
* snappy_wrappers ?
* snappy_pipeline ?

Undecided:

* miniconda

**Comment by ericblanc20** [comment]
Documentation of archive rules improved
